(() => {
  const API = window.LEGECY_API_URL || "";
  const MASCOT = "https://avatars.githubusercontent.com/u/323494663?v=4";
  const esc = (v) => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const short = v => { const s=String(v||""); return s.length>18?`${s.slice(0,8)}…${s.slice(-8)}`:s; };
  const request = async (url, options={}) => { const r=await fetch(`${API}${url}`,{headers:{"Content-Type":"application/json"},...options}); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.detail?.message||d.detail||"Request failed."); return d; };

  function visualTheme(){
    if(document.getElementById("legecyVisualTheme")) return;
    const s=document.createElement("style"); s.id="legecyVisualTheme";
    s.textContent=`
      :root{--bg:#f7faf8!important;--line:#dce7e1!important;--text:#0e1713!important;--muted:#68776f!important;--green:#12b866!important;--green2:#07954f!important;--purple:#7759d9!important}
      body{background:radial-gradient(circle at 82% 2%,rgba(18,184,102,.14),transparent 28%),radial-gradient(circle at 12% 24%,rgba(119,89,217,.07),transparent 23%),#f7faf8!important;color:var(--text)!important}
      body:before{opacity:.28!important;background-image:linear-gradient(rgba(14,23,19,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(14,23,19,.035) 1px,transparent 1px)!important;background-size:44px 44px!important}
      .mark{overflow:hidden!important;border:0!important;background:transparent!important;box-shadow:none!important;width:42px!important;height:42px!important;border-radius:50%!important;padding:0!important}
      .mark::before{content:"";display:block;width:100%;height:100%;background:url('${MASCOT}') center/cover no-repeat;border-radius:50%;box-shadow:0 5px 18px rgba(18,184,102,.24);}
      .mark{font-size:0!important}.brand{gap:11px}.logo{font-size:18px!important;color:#0e1713!important}.logo span{color:#12b866!important}
      .header-right{color:#68776f!important}.dot{background:#12b866!important;box-shadow:0 0 10px rgba(18,184,102,.35)!important}
      .hero{position:relative;overflow:visible}.hero:after{content:"";position:absolute;right:-80px;top:-30px;width:430px;height:430px;border:1px solid rgba(18,184,102,.10);border-radius:50%;pointer-events:none;animation:leOrbit 18s linear infinite}.hero:before{content:"";position:absolute;right:45px;top:45px;width:250px;height:250px;border:1px dashed rgba(119,89,217,.12);border-radius:50%;pointer-events:none;animation:leOrbit 12s linear infinite reverse}
      .le-visual{position:absolute;right:25px;top:20px;width:370px;height:370px;pointer-events:none;z-index:0}.le-mascot{position:absolute;right:20px;top:20px;width:285px;height:285px;border-radius:50%;object-fit:cover;filter:drop-shadow(0 22px 32px rgba(18,184,102,.20));animation:leFloat 5s ease-in-out infinite}.le-glow{position:absolute;right:12px;top:12px;width:300px;height:300px;border-radius:50%;background:radial-gradient(circle,rgba(18,184,102,.20),rgba(18,184,102,.06) 48%,transparent 70%);animation:lePulse 3.5s ease-in-out infinite}.le-orbit{position:absolute;inset:5px;border:1px solid rgba(18,184,102,.15);border-radius:50%;animation:leOrbit 16s linear infinite}.le-orbit:after{content:"";position:absolute;left:8%;top:12%;width:9px;height:9px;border-radius:50%;background:#12b866;box-shadow:0 0 18px rgba(18,184,102,.75)}.le-float-card{position:absolute;background:rgba(255,255,255,.90);backdrop-filter:blur(12px);border:1px solid #dce9e2;border-radius:13px;padding:11px 13px;box-shadow:0 14px 30px rgba(20,48,34,.10);font-size:11px;color:#52635a}.le-float-card b{display:block;font-size:16px;color:#0e1713;margin-top:3px}.le-float-a{left:0;top:75px}.le-float-b{right:-8px;top:155px}.le-float-c{left:35px;bottom:5px}
      .search{position:relative;z-index:2!important;background:rgba(255,255,255,.94)!important;border-color:#d5e3db!important;box-shadow:0 18px 50px rgba(22,56,39,.10)!important}.search button{background:#12b866!important}.search button:hover{background:#07954f!important}
      .card,.walletbar{background:rgba(255,255,255,.90)!important;border-color:#dce7e1!important;box-shadow:0 12px 34px rgba(20,48,34,.07)!important;backdrop-filter:blur(8px)}
      .metric,.le-mini{background:#f7faf8!important;border-color:#e0eae4!important}.signal{background:#f1f7f3!important;border-color:#dce8e1!important;color:#42534a!important}.le-btn{background:#fff!important;color:#405149!important;border-color:#d3e0d9!important}.le-btn.primary{background:#12b866!important;color:#fff!important;border-color:#12b866!important}.le-input{background:#f7faf8!important;color:#0e1713!important;border-color:#dce7e1!important}
      .score-ring{background:conic-gradient(#12b866 var(--score,0),#e1eae5 0)!important}.score-ring:after,.sm-score:after{background:#fff!important;border-color:#e0e9e4!important}.sm-score{background:conic-gradient(#7759d9 var(--sm-score,0),#e6e2f4 0)!important}
      .le-nav{display:flex;align-items:center;gap:21px;margin-left:auto;margin-right:24px}.le-nav a{font-size:12px;color:#526159;text-decoration:none;font-weight:700}.le-nav a:hover,.le-nav .le-nav-active{color:#12a85d}.le-social{display:inline-flex;align-items:center;gap:8px}.le-social a{color:#526159;text-decoration:none}.le-social a:hover{color:#12a85d}
      @keyframes leFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-9px)}}@keyframes lePulse{0%,100%{transform:scale(.96);opacity:.7}50%{transform:scale(1.04);opacity:1}}@keyframes leOrbit{to{transform:rotate(360deg)}}
      @media(max-width:900px){.le-visual{opacity:.45;right:-70px}.le-nav{gap:12px;margin-right:12px}.le-nav a:nth-child(n+4){display:none}}
      @media(max-width:650px){.le-visual{display:none}.le-nav{display:none}}
    `; document.head.appendChild(s);
  }
  function navigation(){
    const h=document.querySelector("header"); if(!h||document.getElementById("legecyMainNav")) return;
    const n=document.createElement("nav"); n.id="legecyMainNav"; n.className="le-nav";
    n.innerHTML=`<a class="le-nav-active" href="/">Intelligence</a><a href="/#dashboard">Analysis</a><a href="/docs/">Docs</a><a href="https://github.com/BuildLEGECY/LEGECY" target="_blank" rel="noopener noreferrer">GitHub</a><a href="https://x.com/BuildLEGECY" target="_blank" rel="noopener noreferrer">𝕏</a>`;
    h.insertBefore(n,h.querySelector(".header-right")||null);
  }
  function footerLinks(){ const f=document.querySelector("footer"); if(!f||document.getElementById("legecyFooterSocial"))return; const x=document.createElement("span"); x.id="legecyFooterSocial"; x.className="le-social"; x.innerHTML=`<a href="/docs/">Docs</a><span>·</span><a href="https://x.com/BuildLEGECY" target="_blank" rel="noopener noreferrer">𝕏 @BuildLEGECY</a><span>·</span><a href="https://github.com/BuildLEGECY/LEGECY" target="_blank" rel="noopener noreferrer">GitHub</a>`; f.appendChild(x); }
  function heroVisual(){ if(document.getElementById("legecyHeroVisual"))return; const hero=document.querySelector(".hero"); if(!hero)return; const v=document.createElement("div"); v.id="legecyHeroVisual"; v.className="le-visual"; v.innerHTML=`<div class="le-glow"></div><div class="le-orbit"></div><img class="le-mascot" src="${MASCOT}" alt="LEGECY mascot"><div class="le-float-card le-float-a">Smart Money<b>Detected</b></div><div class="le-float-card le-float-b">Reputation<b>82 / 100</b></div><div class="le-float-card le-float-c">On-chain<b>Intelligence</b></div>`; hero.appendChild(v); }
  function panels(){
    if(document.getElementById("legecyEnhancements"))return; const d=document.getElementById("dashboard"); if(!d)return;
    const s=document.createElement("section"); s.id="legecyEnhancements"; s.className="le-enhance-grid"; s.innerHTML=`<div class="card"><div class="section-title"><h3>Watchlist</h3><span>Tracked wallets</span></div><div class="le-form"><input id="leWatchLabel" class="le-input" placeholder="Label for current wallet"><button id="leWatchAdd" class="le-btn primary">Add wallet</button></div><div id="leWatchCurrent" class="le-current">Analyze a wallet to add it to your watchlist.</div><div id="leWatchList" class="le-empty">Loading watchlist…</div></div><div class="card"><div class="section-title"><h3>Smart Money Ranking</h3><span>Confidence-adjusted</span></div><div class="le-form"><input id="leRankWallet" class="le-input" placeholder="Seed wallet address"><button id="leRankRun" class="le-btn primary">Rank wallets</button></div><div id="leRankStatus" class="le-current">Use the analyzed wallet as a seed, or enter another wallet.</div><div id="leRankList" class="le-empty">No ranking loaded.</div></div>`; d.appendChild(s);
    document.getElementById("leWatchAdd").onclick=addWallet; document.getElementById("leRankRun").onclick=rank; loadWatchlist();
  }
  async function loadWatchlist(){ const t=document.getElementById("leWatchList"); if(!t)return; try{const a=await request("/watchlist"); t.innerHTML=a.length?a.map(i=>`<div class="le-row"><div><div class="le-wallet">${esc(short(i.wallet))}</div><div class="le-meta">${esc(i.label||"Unlabeled")}</div></div><button class="le-btn" data-rm="${esc(i.wallet)}">Remove</button></div>`).join(""):"<div class='le-empty'>No wallets are being watched.</div>"; t.querySelectorAll("[data-rm]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{await request(`/watchlist/${encodeURIComponent(b.dataset.rm)}`,{method:"DELETE"});await loadWatchlist()}catch(e){alert(e.message);b.disabled=false}});}catch(e){t.innerHTML=`<div class='le-error'>${esc(e.message)}</div>`;} }
  async function addWallet(){const w=currentWallet;if(!w){alert("Analyze a wallet first.");return}const b=document.getElementById("leWatchAdd");b.disabled=true;try{await request("/watchlist",{method:"POST",body:JSON.stringify({wallet:w,label:document.getElementById("leWatchLabel").value.trim()})});document.getElementById("leWatchLabel").value="";await loadWatchlist()}catch(e){alert(e.message)}finally{b.disabled=false}}
  async function rank(){const w=document.getElementById("leRankWallet").value.trim(),st=document.getElementById("leRankStatus"),t=document.getElementById("leRankList"),b=document.getElementById("leRankRun");if(!w){st.textContent="Enter a seed wallet address.";return}b.disabled=true;st.textContent="Finding and ranking wallets…";try{const d=await request(`/rank/${encodeURIComponent(w)}`),rows=Array.isArray(d.ranked_wallets)?d.ranked_wallets:[];st.textContent=`${rows.length} wallet${rows.length===1?"":"s"} passed the confidence filter.`;t.innerHTML=rows.length?rows.slice(0,10).map(r=>`<div class="le-row"><div class="le-rank">#${esc(r.rank)}</div><div style="flex:1"><div class="le-wallet">${esc(short(r.wallet))}</div><div class="le-grid"><div class="le-mini"><b>${esc(r.ranking_score)}</b><span>Ranking</span></div><div class="le-mini"><b>${esc(r.smart_money_score)}</b><span>Smart Money</span></div><div class="le-mini"><b>${esc(r.reputation_score)}</b><span>Reputation</span></div><div class="le-mini"><b>${esc(r.confidence)}</b><span>Confidence</span></div></div></div></div>`).join(""):"<div class='le-empty'>No wallets met the current confidence threshold.</div>"}catch(e){st.textContent="Ranking failed.";t.innerHTML=`<div class='le-error'>${esc(e.message)}</div>`}finally{b.disabled=false}}
  let currentWallet="";
  function hook(){const original=window.renderProfile;if(typeof original!=="function"||window.__legecyProfileHooked)return;window.__legecyProfileHooked=true;window.renderProfile=function(data){original.apply(this,arguments);currentWallet=data?.wallet||"";const c=document.getElementById("leWatchCurrent"),r=document.getElementById("leRankWallet");if(c)c.textContent=currentWallet?`Current wallet: ${short(currentWallet)}`:"Analyze a wallet to add it to your watchlist.";if(r&&currentWallet)r.value=currentWallet;};}
  function init(){visualTheme();navigation();footerLinks();heroVisual();panels();hook();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();