(() => {
  const API = window.LEGECY_API_URL || "";
  const MASCOT = "https://avatars.githubusercontent.com/u/323494663?v=4";
  const esc = (v) => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const short = v => { const s=String(v||""); return s.length>18 ? `${s.slice(0,8)}…${s.slice(-8)}` : s; };
  const request = async (url, options={}) => { const r=await fetch(`${API}${url}`,{headers:{"Content-Type":"application/json"},...options}); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.detail?.message||d.detail||"Request failed."); return d; };

  function visualTheme(){
    if(document.getElementById("legecyFinalVisualTheme")) return;
    const s=document.createElement("style"); s.id="legecyFinalVisualTheme"; s.textContent=`
      :root{--bg:#f7faf8!important;--line:#dce9e3!important;--text:#0b1420!important;--muted:#64756c!important;--green:#08bf68!important;--green2:#079d58!important;--purple:#7657df!important}
      body{background:radial-gradient(circle at 78% 6%,rgba(8,191,104,.14),transparent 30%),radial-gradient(circle at 7% 34%,rgba(118,87,223,.06),transparent 24%),linear-gradient(#fff,#f4faf7)!important;color:var(--text)!important;overflow-x:hidden}
      body:before{opacity:.2!important;background-image:linear-gradient(rgba(11,20,32,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(11,20,32,.04) 1px,transparent 1px)!important;background-size:44px 44px!important}
      .container{width:min(1320px,90%)!important}.mark{width:52px!important;height:52px!important;border:0!important;border-radius:50%!important;overflow:hidden!important;padding:0!important;background:#ecfff5!important;box-shadow:0 8px 28px rgba(8,191,104,.16)!important;font-size:0!important;display:grid!important;place-items:center!important}.mark:before{content:"L"!important;display:grid!important;place-items:center!important;width:100%!important;height:100%!important;background:linear-gradient(145deg,#f6fff9,#e9fff3)!important;color:#0b1420!important;font:900 30px/1 Inter,ui-sans-serif,system-ui,sans-serif!important;letter-spacing:-1px!important}
      header{height:82px!important;background:rgba(255,255,255,.82)!important;border-bottom:1px solid #e1ebe6!important;backdrop-filter:blur(14px);position:relative;z-index:20}.brand{gap:13px!important}.brand .mark img{display:none!important}.logo{font-size:22px!important;color:#0b1420!important;letter-spacing:1.6px!important}.logo span{color:var(--green)!important}
      .header-right{display:flex!important;align-items:center!important;gap:20px!important;color:#64756c!important}.le-nav{display:flex;align-items:center;gap:14px;margin-left:28px;margin-right:28px;order:2}.le-nav a{font-size:13px;color:#17231e;text-decoration:none;font-weight:800}.le-nav a:hover{color:var(--green)}.le-social{display:flex;align-items:center;gap:18px}.le-social a{font-size:14px;color:#17231e;text-decoration:none;font-weight:800}.le-start{display:none!important}
      .le-countdown{display:flex;align-items:center;gap:17px;padding:9px 17px;border:1px solid #d9eee4;border-radius:999px;background:rgba(247,255,251,.9);box-shadow:0 9px 28px rgba(8,191,104,.07);white-space:nowrap;margin-left:28px;order:1}.le-countdown-status{display:flex;align-items:center;gap:9px;padding-right:17px;border-right:1px solid #bfe4d2}.le-countdown-dot{width:9px;height:9px;border-radius:50%;background:var(--green);box-shadow:0 0 12px rgba(8,191,104,.55);animation:leDotPulse 1.8s ease-in-out infinite}.le-countdown-copy strong{display:block;font-size:10px;letter-spacing:.8px;text-transform:uppercase;color:#102019}.le-countdown-copy span{display:block;margin-top:3px;font-size:9px;color:#718078;letter-spacing:.2px}.le-countdown-time{display:flex;align-items:flex-start;gap:8px}.le-countdown-unit{text-align:center;min-width:42px}.le-countdown-unit b{display:block;font:850 20px/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:#079d58;letter-spacing:-1px}.le-countdown-unit span{display:block;margin-top:4px;font-size:8px;color:#718078;text-transform:uppercase;letter-spacing:.7px}.le-countdown-sep{font:800 18px/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:#8eb5a2;padding-top:1px}
      .hero{padding:68px 0 34px!important;min-height:610px!important;position:relative!important}.hero:after{content:"";position:absolute;right:-110px;top:-80px;width:690px;height:690px;border-radius:50%;border:1px solid rgba(8,191,104,.12);box-shadow:0 0 100px rgba(8,191,104,.08);pointer-events:none;z-index:-1}.hero:before{content:"";position:absolute;right:55px;top:60px;width:390px;height:390px;border-radius:50%;border:1px dashed rgba(118,87,223,.13);pointer-events:none;animation:leSpin 22s linear infinite}
      .eyebrow{display:inline-flex!important;padding:7px 12px!important;border:1px solid #ccebdd!important;border-radius:999px!important;background:#f0fff7!important;color:#079d58!important;letter-spacing:2px!important;font-size:10px!important}.hero h1{font-size:clamp(48px,6.1vw,82px)!important;line-height:.95!important;letter-spacing:-4.2px!important;max-width:710px!important;margin-top:18px!important}.hero h1:after{content:"";display:inline-block;width:12px;height:12px;background:var(--green);border-radius:50%;margin-left:5px;box-shadow:0 0 18px rgba(8,191,104,.35)}.hero p{font-size:17px!important;line-height:1.62!important;color:#62746b!important;max-width:680px!important}
      .search{max-width:820px!important;background:rgba(255,255,255,.95)!important;border:1px solid #cce7da!important;border-radius:18px!important;padding:8px!important;box-shadow:0 18px 55px rgba(13,67,43,.1)!important;position:relative;z-index:5}.search input{color:#14221b!important;padding:16px!important}.search input::placeholder{color:#8b9992!important}.search button{min-height:50px!important;padding:0 28px!important;border-radius:13px!important;background:linear-gradient(135deg,#09d879,#07b960)!important;color:#04150d!important;box-shadow:0 8px 22px rgba(8,191,104,.18)!important}
      .le-visual{position:absolute;right:-20px;top:25px;width:565px;height:525px;pointer-events:none;z-index:1}.le-glow{position:absolute;left:80px;top:55px;width:410px;height:410px;border-radius:50%;background:radial-gradient(circle,rgba(8,216,121,.22),rgba(8,191,104,.07) 48%,transparent 70%);animation:lePulse 4s ease-in-out infinite}.le-orbit{position:absolute;left:25px;top:25px;width:500px;height:410px;border:1px solid rgba(8,191,104,.17);border-radius:50%;transform:rotate(-12deg);animation:leSpin 18s linear infinite}.le-orbit:after{content:"";position:absolute;left:10%;top:14%;width:10px;height:10px;border-radius:50%;background:var(--green);box-shadow:0 0 20px rgba(8,191,104,.7)}.le-mascot{position:absolute;width:390px;height:390px;left:100px;top:58px;object-fit:contain;border-radius:50%;filter:drop-shadow(0 25px 35px rgba(8,90,53,.2));animation:leFloat 5s ease-in-out infinite}.le-float-card{position:absolute;min-width:145px;background:rgba(255,255,255,.9);border:1px solid #d5eae0;border-radius:16px;padding:13px 15px;box-shadow:0 15px 35px rgba(15,60,40,.1);backdrop-filter:blur(12px);font-size:11px;color:#53645b}.le-float-card strong{display:block;color:#0b1420;font-size:13px;margin-bottom:5px}.le-float-card b{font-size:21px;color:var(--green)}.le-f1{left:10px;top:85px}.le-f2{right:0;top:160px}.le-f3{left:45px;bottom:28px}.le-f4{right:30px;bottom:70px}
      .le-feature-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:-3px 0 18px;position:relative;z-index:6}.le-feature{display:flex;align-items:center;gap:11px;padding:14px 15px;background:rgba(255,255,255,.88);border:1px solid #dcebe4;border-radius:15px;box-shadow:0 9px 25px rgba(15,60,40,.05)}.le-feature .ico{width:38px;height:38px;border-radius:11px;display:grid;place-items:center;background:#effbf5;color:var(--green);font-size:19px}.le-feature strong{display:block;font-size:12px}.le-feature span{display:block;margin-top:3px;font-size:10px;color:#6d7c74}
      .le-stats{display:grid;grid-template-columns:repeat(4,1fr);background:rgba(255,255,255,.9);border:1px solid #dcebe4;border-radius:18px;overflow:hidden;box-shadow:0 18px 55px rgba(15,60,40,.07);margin:20px 0 50px}.le-stat{padding:21px 24px;border-right:1px solid #e4ede8}.le-stat:last-child{border-right:0}.le-stat b{display:block;font-size:25px;letter-spacing:-.8px}.le-stat span{font-size:11px;color:#6a7972}
      .le-section-intro{display:flex;align-items:end;justify-content:space-between;gap:35px;margin:0 0 20px}.le-section-intro h2{font-size:38px;letter-spacing:-2px;margin:8px 0 0}.le-section-intro p{max-width:480px;margin:0;color:#687870;line-height:1.6;font-size:13px}.le-why{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:42px}.le-why-card{background:#fff;border:1px solid #dceae3;border-radius:18px;padding:22px;min-height:150px;box-shadow:0 10px 32px rgba(15,60,40,.055);transition:.25s}.le-why-card:hover{transform:translateY(-4px);box-shadow:0 18px 42px rgba(15,60,40,.1)}.le-why-card .ico{font-size:23px;color:var(--green)}.le-why-card h3{margin:15px 0 7px;font-size:15px}.le-why-card p{margin:0;color:#6a7971;font-size:11px;line-height:1.6}
      .card,.walletbar{background:rgba(255,255,255,.94)!important;border-color:#dce9e3!important;box-shadow:0 12px 38px rgba(15,60,40,.06)!important}.metric,.le-mini{background:#f7faf8!important;border-color:#e1ebe6!important}.signal{background:#f1f8f4!important;border-color:#dbe9e2!important;color:#4b5b53!important}.score-ring{background:conic-gradient(var(--green) var(--score,0),#e3ece7 0)!important}.score-ring:after,.sm-score:after{background:#fff!important;border-color:#e0ebe5!important}.sm-score{background:conic-gradient(var(--purple) var(--sm-score,0),#e6e2f3 0)!important}.section-title h3,.rep-copy h2,.score,.stat .value,.metric .val,.mini-stat strong,.sm-copy h3{color:#0b1420!important}.label,.section-title span,.metric .name,.stat .sub{color:#73817a!important}.address{color:#43534b!important}.bar{background:#e4ece8!important}.bar i{background:linear-gradient(90deg,#079d58,#08d879)!important}.positive{color:#079d58!important}.negative{color:#d84f5e!important}
      .le-enhance-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.le-form{display:flex;gap:8px;margin-bottom:10px}.le-input{width:100%;border:1px solid #dce5e0;border-radius:10px;background:#f7faf8;color:#101714;padding:10px 11px;outline:0;font:12px inherit}.le-input:focus{border-color:var(--green)}.le-btn{border:1px solid #d3ded8;border-radius:9px;background:#fff;color:#405048;padding:9px 12px;font:700 11px inherit;cursor:pointer}.le-btn.primary{background:var(--green);color:#fff;border-color:var(--green)}.le-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #e1e8e4}.le-row:last-child{border-bottom:0}.le-wallet{font:11px ui-monospace,SFMono-Regular,Menlo,monospace;color:#3d4d45}.le-meta,.le-current{font-size:10px;color:#75837c;margin-top:4px}.le-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.le-mini{border:1px solid #e1e9e4;border-radius:10px;padding:10px}.le-mini b{display:block;font-size:14px;color:#101714}.le-mini span{font-size:9px;color:#718078;text-transform:uppercase;letter-spacing:.7px}.le-rank{font-size:12px;font-weight:850;color:var(--green);width:25px}.le-empty{color:#829088;font-size:11px;padding:8px 0}.le-error{color:#d84f5e;font-size:11px;padding:8px 0}
      footer{border-top-color:#dce9e3!important;color:#73817a!important}
      @keyframes leFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}@keyframes lePulse{0%,100%{transform:scale(.97);opacity:.72}50%{transform:scale(1.04);opacity:1}}@keyframes leSpin{to{transform:rotate(360deg)}}@keyframes leDotPulse{0%,100%{transform:scale(.85);opacity:.72}50%{transform:scale(1.15);opacity:1}}
      @media(max-width:1050px){.le-visual{right:-140px;opacity:.62}.le-countdown{margin-left:18px}.le-nav{gap:10px;margin-left:18px;margin-right:18px}}
      @media(max-width:800px){.hero{min-height:650px!important}.le-visual{position:absolute;right:50%;transform:translateX(50%);top:350px;width:520px;height:360px;opacity:1}.le-mascot{width:270px;height:270px;left:125px;top:25px}.le-glow{width:300px;height:300px;left:110px;top:15px}.le-orbit{width:390px;height:300px;left:65px;top:10px}.le-float-card{transform:scale(.82)}.le-f1{left:35px;top:35px}.le-f2{right:35px;top:75px}.le-f3{left:55px;bottom:5px}.le-f4{right:45px;bottom:20px}.le-nav{display:flex}.le-feature-strip,.le-stats,.le-why{grid-template-columns:1fr 1fr}.le-enhance-grid{grid-template-columns:1fr}.le-section-intro{display:block}.le-section-intro p{margin-top:12px}}
      @media(max-width:680px){header{height:auto!important;min-height:74px!important;padding:12px 0!important;flex-wrap:wrap;gap:10px}.brand{order:1}.le-countdown{order:3;width:100%;margin:0!important;justify-content:center;padding:8px 10px}.le-countdown-status{padding-right:10px}.le-countdown-copy span{display:none}.le-countdown-time{gap:4px}.le-countdown-unit{min-width:34px}.le-countdown-unit b{font-size:16px}.le-countdown-sep{font-size:15px}.le-nav{order:4;margin:0!important;gap:14px}.header-right{order:2;margin-left:auto;gap:12px}.le-social{gap:12px}.le-social a{font-size:13px}}
      @media(max-width:560px){.container{width:94%!important}.mark{width:44px!important;height:44px!important}.logo{font-size:19px!important}.hero{padding-top:42px!important;min-height:650px!important}.hero h1{letter-spacing:-2.6px!important;font-size:clamp(42px,12vw,62px)!important}.hero p{font-size:15px!important}.le-visual{top:360px;width:390px;height:285px}.le-mascot{width:220px;height:220px;left:85px}.le-glow{width:250px;height:250px;left:70px}.le-orbit{width:300px;height:235px;left:45px}.le-float-card{min-width:115px;padding:9px 10px;transform:scale(.72)}.le-f1{left:0;top:25px}.le-f2{right:0;top:55px}.le-f3{left:15px;bottom:0}.le-f4{right:5px;bottom:5px}.search{flex-direction:column}.search button{height:48px}.le-feature-strip,.le-stats,.le-why{grid-template-columns:1fr}.le-stat{border-right:0;border-bottom:1px solid #e4ede8}.le-stat:last-child{border-bottom:0}.le-section-intro h2{font-size:31px}.le-grid{grid-template-columns:1fr 1fr}footer{display:block;line-height:2}}
    `; document.head.appendChild(s);
  }
  function navigation(){const h=document.querySelector("header");if(!h)return;h.innerHTML=`<div class="brand"><div class="mark" aria-label="LEGECY logo" title="LEGECY"><span style="display:none">L</span></div><div class="logo">LEGECY<span>.</span></div></div><div class="le-countdown" aria-label="Next LEGECY milestone countdown"><div class="le-countdown-status"><i class="le-countdown-dot"></i><div class="le-countdown-copy"><strong>NEXT MILESTONE</strong><span>A SMARTER ON-CHAIN FUTURE</span></div></div><div class="le-countdown-time"><div class="le-countdown-unit"><b id="leDays">00</b><span>Days</span></div><div class="le-countdown-sep">:</div><div class="le-countdown-unit"><b id="leHours">00</b><span>Hours</span></div><div class="le-countdown-sep">:</div><div class="le-countdown-unit"><b id="leMinutes">00</b><span>Minutes</span></div><div class="le-countdown-sep">:</div><div class="le-countdown-unit"><b id="leSeconds">00</b><span>Seconds</span></div></div></div><nav class="le-nav"><a href="/docs/">Docs</a></nav><div class="header-right"><div class="le-social"><a href="https://x.com/BuildLEGECY" target="_blank" rel="noopener noreferrer" aria-label="LEGECY on X">𝕏</a><a href="https://github.com/BuildLEGECY/LEGECY" target="_blank" rel="noopener noreferrer" aria-label="LEGECY on GitHub">GitHub</a></div></div>`; startCountdown()}
  function startCountdown(){
    const target = new Date("2026-10-01T20:00:00+05:30").getTime();
    const ids={d:"leDays",h:"leHours",m:"leMinutes",s:"leSeconds"};
    const tick=()=>{const diff=Math.max(0,target-Date.now());const total=Math.floor(diff/1000);const d=Math.floor(total/86400);const h=Math.floor(total%86400/3600);const m=Math.floor(total%3600/60);const sec=total%60;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=String(v).padStart(2,"0")};set(ids.d,d);set(ids.h,h);set(ids.m,m);set(ids.s,sec);if(diff<=0){const e=document.querySelector(".le-countdown-copy strong");if(e)e.textContent="MILESTONE LIVE"}};
    tick();
    if(window.__legecyCountdownTimer) clearInterval(window.__legecyCountdownTimer);
    window.__legecyCountdownTimer=setInterval(tick,1000);
  }
  function heroVisual(){if(document.getElementById("legecyHeroVisual"))return;const hero=document.querySelector(".hero");if(!hero)return;const v=document.createElement("div");v.id="legecyHeroVisual";v.className="le-visual";v.innerHTML=`<div class="le-glow"></div><div class="le-orbit"></div><img class="le-mascot" src="${MASCOT}" alt="LEGECY mascot"><div class="le-float-card le-f1"><strong>Smart Money</strong><b>+82%</b><br>Detected</div><div class="le-float-card le-f2"><strong>On-chain Signals</strong><b>100+</b><br>Analyzed</div><div class="le-float-card le-f3"><strong>Reputation</strong><b>82</b><br>Wallet score</div><div class="le-float-card le-f4"><strong>Live Intelligence</strong><b>●</b><br>Solana activity</div>`;hero.appendChild(v)}
  function heroExtras(){if(document.getElementById("legecyFeatureStrip"))return;const hero=document.querySelector(".hero");if(!hero)return;const fs=document.createElement("div");fs.id="legecyFeatureStrip";fs.className="le-feature-strip";fs.innerHTML=`<div class="le-feature"><div class="ico">⌕</div><div><strong>Wallet Intelligence</strong><span>Deep wallet analysis</span></div></div><div class="le-feature"><div class="ico">▥</div><div><strong>Smart Money</strong><span>Find top performers</span></div></div><div class="le-feature"><div class="ico">▣</div><div><strong>Wallet Comparison</strong><span>Compare wallets</span></div></div><div class="le-feature"><div class="ico">◈</div><div><strong>On-chain Insights</strong><span>Data you can trust</span></div></div>`;hero.insertAdjacentElement("afterend",fs);const stats=document.createElement("div");stats.className="le-stats";stats.innerHTML=`<div class="le-stat"><b>1M+</b><span>Wallets Analyzed</span></div><div class="le-stat"><b>100+</b><span>On-chain Signals</span></div><div class="le-stat"><b>Real-time</b><span>Data Updates</span></div><div class="le-stat"><b>Built</b><span>In Public</span></div>`;fs.insertAdjacentElement("afterend",stats);const intro=document.createElement("div");intro.className="le-section-intro";intro.innerHTML=`<div><div class="eyebrow">WHY LEGECY</div><h2>More Than Just <span style="color:var(--green)">Data.</span></h2></div><p>We turn on-chain data into actionable intelligence, so you can make smarter decisions.</p>`;stats.insertAdjacentElement("afterend",intro);const why=document.createElement("div");why.className="le-why";why.innerHTML=`<div class="le-why-card"><div class="ico">◉</div><h3>Analyze Wallets</h3><p>Get deep insights into trading behavior, reputation and activity.</p></div><div class="le-why-card"><div class="ico">◌</div><h3>Find Smart Money</h3><p>Discover stronger wallets using confidence-aware intelligence.</p></div><div class="le-why-card"><div class="ico">▦</div><h3>Compare Wallets</h3><p>See wallet performance side by side with clear signals.</p></div><div class="le-why-card"><div class="ico">⌁</div><h3>Track Opportunities</h3><p>Keep important wallets close with persistent watchlists.</p></div>`;intro.insertAdjacentElement("afterend",why)}
  let currentWallet="";
  function panels(){if(document.getElementById("legecyEnhancements"))return;const d=document.getElementById("dashboard");if(!d)return;const s=document.createElement("section");s.id="legecyEnhancements";s.className="le-enhance-grid";s.innerHTML=`<div class="card"><div class="section-title"><h3>Watchlist</h3><span>Tracked wallets</span></div><div class="le-form"><input id="leWatchLabel" class="le-input" placeholder="Label for current wallet"><button id="leWatchAdd" class="le-btn primary">Add wallet</button></div><div id="leWatchCurrent" class="le-current">Analyze a wallet to add it to your watchlist.</div><div id="leWatchList" class="le-empty">Loading watchlist…</div></div><div class="card"><div class="section-title"><h3>Smart Money Ranking</h3><span>Confidence-adjusted</span></div><div class="le-form"><input id="leRankWallet" class="le-input" placeholder="Seed wallet address"><button id="leRankRun" class="le-btn primary">Rank wallets</button></div><div id="leRankStatus" class="le-current">Use the analyzed wallet as a seed, or enter another wallet.</div><div id="leRankList" class="le-empty">No ranking loaded.</div></div>`;d.appendChild(s);document.getElementById("leWatchAdd").onclick=addWallet;document.getElementById("leRankRun").onclick=rank;loadWatchlist()}
  async function loadWatchlist(){const t=document.getElementById("leWatchList");if(!t)return;try{const a=await request("/watchlist");t.innerHTML=a.length?a.map(i=>`<div class="le-row"><div><div class="le-wallet">${esc(short(i.wallet))}</div><div class="le-meta">${esc(i.label||"Unlabeled")}</div></div><button class="le-btn" data-rm="${esc(i.wallet)}">Remove</button></div>`).join(""):"<div class='le-empty'>No wallets are being watched.</div>";t.querySelectorAll("[data-rm]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{await request(`/watchlist/${encodeURIComponent(b.dataset.rm)}`,{method:"DELETE"});await loadWatchlist()}catch(e){alert(e.message);b.disabled=false}})}catch(e){t.innerHTML=`<div class='le-error'>${esc(e.message)}</div>`}}
  async function addWallet(){if(!currentWallet){alert("Analyze a wallet first.");return}const b=document.getElementById("leWatchAdd");b.disabled=true;try{await request("/watchlist",{method:"POST",body:JSON.stringify({wallet:currentWallet,label:document.getElementById("leWatchLabel").value.trim()})});document.getElementById("leWatchLabel").value="";await loadWatchlist()}catch(e){alert(e.message)}finally{b.disabled=false}}
  async function rank(){const w=document.getElementById("leRankWallet").value.trim(),st=document.getElementById("leRankStatus"),t=document.getElementById("leRankList"),b=document.getElementById("leRankRun");if(!w){st.textContent="Enter a seed wallet address.";return}b.disabled=true;st.textContent="Finding and ranking wallets…";try{const d=await request(`/rank/${encodeURIComponent(w)}`),rows=Array.isArray(d.ranked_wallets)?d.ranked_wallets:[];st.textContent=`${rows.length} wallet${rows.length===1?"":"s"} passed the confidence filter.`;t.innerHTML=rows.length?rows.slice(0,10).map(r=>`<div class="le-row"><div class="le-rank">#${esc(r.rank)}</div><div style="flex:1"><div class="le-wallet">${esc(short(r.wallet))}</div><div class="le-grid"><div class="le-mini"><b>${esc(r.ranking_score)}</b><span>Ranking</span></div><div class="le-mini"><b>${esc(r.smart_money_score)}</b><span>Smart Money</span></div><div class="le-mini"><b>${esc(r.reputation_score)}</b><span>Reputation</span></div><div class="le-mini"><b>${esc(r.confidence)}</b><span>Confidence</span></div></div></div></div>`).join(""):"<div class='le-empty'>No wallets met the current confidence threshold.</div>"}catch(e){st.textContent="Ranking failed.";t.innerHTML=`<div class='le-error'>${esc(e.message)}</div>`}finally{b.disabled=false}}
  function hook(){const original=window.renderProfile;if(typeof original!=="function"||window.__legecyFinalProfileHook)return;window.__legecyFinalProfileHook=true;window.renderProfile=function(data){original.apply(this,arguments);currentWallet=data?.wallet||"";const c=document.getElementById("leWatchCurrent"),r=document.getElementById("leRankWallet");if(c)c.textContent=currentWallet?`Current wallet: ${short(currentWallet)}`:"Analyze a wallet to add it to your watchlist.";if(r&&currentWallet)r.value=currentWallet;};}
  function footer(){const f=document.querySelector("footer");if(!f)return;f.innerHTML=`<div><strong style="color:#0b1420">LEGECY.</strong> · Solana Wallet Intelligence</div><div>DATA <span style="color:var(--green)">→</span> INTELLIGENCE <span style="color:var(--green)">→</span> OPPORTUNITY</div><div>Built in public.</div>`}
  function init(){visualTheme();navigation();heroVisual();heroExtras();panels();hook();footer()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();