(()=>{
  if(window.__legecyPremiumVisual) return;
  window.__legecyPremiumVisual=true;
  const css=`
  .le-premium-hero{position:absolute;right:-15px;top:5px;width:620px;height:520px;z-index:1;pointer-events:none}
  .le-premium-stage{position:absolute;inset:0;filter:drop-shadow(0 24px 38px rgba(18,92,65,.14))}
  .le-premium-core{position:absolute;left:215px;top:135px;width:190px;height:140px;transform:perspective(700px) rotateX(7deg) rotateY(-8deg);animation:leCoreFloat 5s ease-in-out infinite}
  .le-wallet-body{position:absolute;inset:0;border-radius:25px;background:linear-gradient(145deg,#073d30,#0b8762 48%,#062e27);border:1px solid rgba(125,255,214,.75);box-shadow:inset 0 0 28px rgba(74,255,196,.22),0 22px 45px rgba(0,65,46,.28)}
  .le-wallet-body:before{content:"";position:absolute;inset:9px;border-radius:18px;border:1px solid rgba(129,255,217,.3)}
  .le-wallet-slot{position:absolute;right:-12px;top:50px;width:25px;height:45px;border-radius:8px;background:#05291f;border:1px solid #36dba7;box-shadow:0 0 18px rgba(8,216,121,.28)}
  .le-solana-mark{position:absolute;left:62px;top:35px;width:68px;height:55px}
  .le-solana-mark i{position:absolute;left:0;width:58px;height:12px;border-radius:3px;transform:skewX(-28deg);background:linear-gradient(90deg,#8b79ff,#55f0c0);box-shadow:0 0 15px rgba(91,228,190,.28)}
  .le-solana-mark i:nth-child(1){top:0}.le-solana-mark i:nth-child(2){top:20px;left:9px}.le-solana-mark i:nth-child(3){top:40px}
  .le-premium-orbit{position:absolute;left:85px;top:105px;width:450px;height:310px;border:1px solid rgba(9,191,104,.25);border-radius:50%;transform:rotate(-12deg);animation:lePremiumSpin 18s linear infinite}
  .le-premium-orbit:after{content:"";position:absolute;left:13%;top:7%;width:8px;height:8px;border-radius:50%;background:#08bf68;box-shadow:0 0 17px rgba(8,191,104,.65)}
  .le-premium-orbit2{position:absolute;left:105px;top:82px;width:405px;height:355px;border:1px dashed rgba(118,87,223,.22);border-radius:50%;transform:rotate(19deg);animation:lePremiumSpinReverse 24s linear infinite}
  .le-premium-ring{position:absolute;left:185px;top:300px;width:250px;height:74px;border:1px solid rgba(8,191,104,.32);border-radius:50%;box-shadow:0 0 35px rgba(8,191,104,.12),inset 0 0 25px rgba(8,191,104,.08);transform:rotate(-5deg);animation:leRingPulse 3.8s ease-in-out infinite}
  .le-premium-ring:before,.le-premium-ring:after{content:"";position:absolute;inset:13px;border-radius:50%;border:1px solid rgba(118,87,223,.22)}.le-premium-ring:after{inset:26px;border-color:rgba(8,191,104,.28)}
  .le-network{position:absolute;inset:0;width:100%;height:100%;overflow:visible}
  .le-network path{fill:none;stroke-linecap:round;stroke-width:1.3;opacity:.48}.le-network .g{stroke:#08bf68}.le-network .p{stroke:#7657df}.le-network circle{stroke:#fff;stroke-width:1.2}.le-network .ng{fill:#08bf68;filter:drop-shadow(0 0 5px rgba(8,191,104,.65))}.le-network .np{fill:#7657df;filter:drop-shadow(0 0 5px rgba(118,87,223,.6))}
  .le-premium-node{position:absolute;width:68px;height:68px;border-radius:15px;background:linear-gradient(145deg,#062e27,#10a77a);border:1px solid rgba(102,255,209,.45);box-shadow:0 14px 30px rgba(8,92,64,.18),inset 0 0 16px rgba(86,255,202,.13);display:grid;place-items:center;animation:leNodeFloat 4.5s ease-in-out infinite}
  .le-premium-node:before{content:"";width:27px;height:27px;border:2px solid #a1ffe0;border-radius:6px;transform:rotate(45deg);opacity:.8}.le-premium-node:after{content:"";position:absolute;width:9px;height:9px;border-radius:50%;background:#fff;box-shadow:0 0 15px rgba(255,255,255,.8)}
  .le-node-a{left:95px;top:75px}.le-node-b{right:63px;top:72px;animation-delay:-1s}.le-node-c{left:60px;bottom:74px;animation-delay:-2s}.le-node-d{right:85px;bottom:45px;animation-delay:-3s}
  .le-premium-label{position:absolute;min-width:148px;padding:12px 14px;border:1px solid #cfe9dd;border-radius:14px;background:rgba(255,255,255,.9);box-shadow:0 12px 28px rgba(16,72,49,.08);backdrop-filter:blur(12px);font-size:11px;color:#5f7067}
  .le-premium-label strong{display:block;color:#0b1420;font-size:12px;margin-bottom:4px}.le-premium-label span{font-size:10px}.le-label-a{left:10px;top:93px}.le-label-b{right:0;top:120px}.le-label-c{left:12px;bottom:43px}.le-label-d{right:3px;bottom:75px}
  .le-premium-live{display:inline-flex!important;align-items:center;gap:7px;color:#079d58!important}.le-premium-live:before{content:"";width:7px;height:7px;border-radius:50%;background:#08bf68;box-shadow:0 0 12px rgba(8,191,104,.7);animation:leLivePulse 1.5s ease-in-out infinite}
  .le-premium-milestone{display:flex;align-items:center;gap:12px;padding:13px 17px;border:1px solid #d7ebe2;border-radius:16px;background:rgba(255,255,255,.86);box-shadow:0 10px 30px rgba(15,60,40,.05)}
  .le-premium-milestone .dot{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:#f0eaff;color:#7657df;font-size:16px}.le-premium-milestone strong{display:block;font-size:11px;letter-spacing:1px;text-transform:uppercase}.le-premium-milestone span{display:block;margin-top:4px;font-size:10px;color:#718078}
  .le-premium-icons .ico{width:40px!important;height:40px!important;border-radius:50%!important;background:#effbf5!important;border:1px solid #d9eee4!important;font-size:0!important;position:relative}.le-premium-icons .ico:before{content:"";width:17px;height:17px;border:2px solid currentColor;border-radius:4px;display:block}.le-premium-icons .le-purple{color:#7657df!important;background:#f1edff!important;border-color:#e3ddff!important}
  @keyframes leCoreFloat{0%,100%{transform:perspective(700px) rotateX(7deg) rotateY(-8deg) translateY(0)}50%{transform:perspective(700px) rotateX(7deg) rotateY(-8deg) translateY(-8px)}}
  @keyframes leNodeFloat{0%,100%{transform:translateY(0) rotate(0deg)}50%{transform:translateY(-9px) rotate(2deg)}}@keyframes lePremiumSpin{to{transform:rotate(348deg)}}@keyframes lePremiumSpinReverse{to{transform:rotate(-341deg)}}@keyframes leRingPulse{0%,100%{opacity:.7;transform:rotate(-5deg) scale(.98)}50%{opacity:1;transform:rotate(-5deg) scale(1.03)}}@keyframes leLivePulse{0%,100%{transform:scale(.8);opacity:.65}50%{transform:scale(1.25);opacity:1}}
  @media(max-width:1050px){.le-premium-hero{right:-180px;opacity:.55}.hero{position:relative!important}}
  @media(max-width:800px){.le-premium-hero{position:absolute;right:50%;transform:translateX(50%);top:345px;width:520px;height:360px;opacity:.9}.le-premium-core{left:190px;top:92px;transform:scale(.78)}.le-premium-orbit{left:70px;top:65px;width:390px;height:255px}.le-premium-orbit2{left:90px;top:50px;width:350px;height:285px}.le-premium-ring{left:150px;top:230px;transform:scale(.8)}.le-node-a{left:65px;top:55px}.le-node-b{right:42px;top:45px}.le-node-c{left:35px;bottom:25px}.le-node-d{right:45px;bottom:15px}.le-premium-label{transform:scale(.8)}.le-label-a{left:0;top:55px}.le-label-b{right:-10px;top:70px}.le-label-c{left:0;bottom:5px}.le-label-d{right:-8px;bottom:10px}}
  @media(max-width:560px){.le-premium-hero{top:350px;width:390px;height:290px}.le-premium-core{left:137px;top:75px;transform:scale(.58)}.le-premium-orbit{left:45px;top:48px;width:300px;height:210px}.le-premium-orbit2{left:65px;top:38px;width:270px;height:235px}.le-premium-ring{left:112px;top:190px;transform:scale(.62)}.le-premium-node{width:48px;height:48px;border-radius:11px}.le-premium-node:before{width:18px;height:18px}.le-node-a{left:40px;top:40px}.le-node-b{right:25px;top:32px}.le-node-c{left:20px;bottom:15px}.le-node-d{right:28px;bottom:5px}.le-premium-label{min-width:105px;padding:8px 9px;font-size:9px;transform:scale(.7)}.le-premium-label strong{font-size:10px}.le-label-a{left:-8px;top:38px}.le-label-b{right:-17px;top:50px}.le-label-c{left:-7px;bottom:-2px}.le-label-d{right:-18px;bottom:0}.hero{min-height:620px!important}}
  `;
  const st=document.createElement('style');st.id='legecyPremiumVisualCss';st.textContent=css;document.head.appendChild(st);

  function header(){const h=document.querySelector('header');if(!h)return;h.innerHTML=`<div class="brand"><div class="mark" aria-label="LEGECY logo"><span style="display:none">L</span></div><div class="logo">LEGECY<span>.</span></div><div class="le-countdown" style="margin-left:18px"><div class="le-countdown-status"><i class="le-countdown-dot"></i><div class="le-countdown-copy"><strong>NEXT MILESTONE</strong><span>A SMARTER ON-CHAIN FUTURE</span></div></div><div class="le-countdown-time"><div class="le-countdown-unit"><b id="leDays">00</b><span>Days</span></div><div class="le-countdown-sep">:</div><div class="le-countdown-unit"><b id="leHours">00</b><span>Hours</span></div><div class="le-countdown-sep">:</div><div class="le-countdown-unit"><b id="leMinutes">00</b><span>Minutes</span></div><div class="le-countdown-sep">:</div><div class="le-countdown-unit"><b id="leSeconds">00</b><span>Seconds</span></div></div></div></div><div class="header-right"><div class="le-social"><a href="/docs/">Docs</a><a href="https://x.com/BuildLEGECY" target="_blank" rel="noopener noreferrer">𝕏</a><a href="https://github.com/BuildLEGECY/LEGECY" target="_blank" rel="noopener noreferrer">GitHub</a></div></div>`;startCountdown()}
  function startCountdown(){const target=new Date('2026-10-01T20:00:00+05:30').getTime();const tick=()=>{const total=Math.max(0,Math.floor((target-Date.now())/1000));const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=String(v).padStart(2,'0')};set('leDays',Math.floor(total/86400));set('leHours',Math.floor(total%86400/3600));set('leMinutes',Math.floor(total%3600/60));set('leSeconds',total%60)};tick();if(window.__legecyPremiumCountdown)clearInterval(window.__legecyPremiumCountdown);window.__legecyPremiumCountdown=setInterval(tick,1000)}
  function hero(){const old=document.getElementById('legecyHeroVisual');if(old)old.remove();const hero=document.querySelector('.hero');if(!hero)return;hero.style.position='relative';const v=document.createElement('div');v.className='le-premium-hero';v.innerHTML=`<svg class="le-network" viewBox="0 0 620 520" aria-hidden="true"><path class="g" d="M92 111 C170 75 204 105 250 148 S355 207 430 118 S522 95 548 139"/><path class="g" d="M62 386 C150 335 178 314 231 306 S365 355 434 391 S515 389 560 330"/><path class="p" d="M88 205 C170 184 215 228 270 260 S370 302 440 238 S511 185 552 211"/><path class="p" d="M120 432 C191 390 234 360 298 337 S408 303 500 265"/><circle class="ng" cx="250" cy="148" r="4"/><circle class="ng" cx="430" cy="118" r="4"/><circle class="np" cx="270" cy="260" r="4"/><circle class="np" cx="440" cy="238" r="4"/><circle class="ng" cx="434" cy="391" r="4"/><circle class="np" cx="500" cy="265" r="4"/></svg><div class="le-premium-stage"><div class="le-premium-orbit"></div><div class="le-premium-orbit2"></div><div class="le-premium-ring"></div><div class="le-premium-core"><div class="le-wallet-body"><div class="le-solana-mark"><i></i><i></i><i></i></div><div class="le-wallet-slot"></div></div></div><div class="le-premium-node le-node-a"></div><div class="le-premium-node le-node-b"></div><div class="le-premium-node le-node-c"></div><div class="le-premium-node le-node-d"></div><div class="le-premium-label le-label-a"><strong>Transactions</strong><span>Live on-chain data</span></div><div class="le-premium-label le-label-b"><strong>Behavior</strong><span>Pattern analysis</span></div><div class="le-premium-label le-label-c"><strong>Opportunities</strong><span>Find what's next</span></div><div class="le-premium-label le-label-d"><strong>Intelligence</strong><span>Turn data into alpha</span></div></div>`;hero.appendChild(v)}
  function polish(){document.querySelectorAll('.le-feature, .le-why-card').forEach((el,i)=>{el.classList.add('le-premium-icons');const ico=el.querySelector('.ico');if(ico&&i%4===1)ico.classList.add('le-purple')});document.querySelectorAll('.le-stat').forEach((el,i)=>{if(i===3){el.innerHTML='<div class="le-premium-live" style="font-weight:850;font-size:25px">Live Intelligence</div><span>Real-time Solana activity</span>'}});document.querySelectorAll('.le-float-card').forEach(x=>x.style.display='none');const fs=document.querySelector('.le-feature-strip');if(fs)fs.style.marginTop='12px';const stats=document.querySelector('.le-stats');if(stats)stats.style.marginTop='22px'}
  function init(){header();hero();polish()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else setTimeout(init,0);
})();
